### ISSUE TITLE
[Victory] Multiple _GEN file for One Rule

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-ibex-ui#154] opened 2019-05-14 12:18 UTC
Once we select and do apply match for axiom rule or any rule, it gives more than one matches. which makes difficult to understand and select match among them.

![image](https://user-images.githubusercontent.com/45486055/57697236-10ef6b80-7653-11e9-96ce-4fa1d2049f90.png)

**Comment by anthonyanjorin** [comment] 2019-05-14 12:24
I don’t understand the problem.  The tgg yields multiple matches - that is the way it works in this case and is not Victory‘s fault.

**Comment by LegionaryCohort** [comment] 2019-05-15 10:59
While this is working as intended, I do see potential for improvement here. It would be good to have some way of differentiating matches by their name.
I can't really think of a general way to generate such a unique name though.

**Comment by shub1989** [comment] 2019-05-15 11:51
Yeah they do produce  multiple matches,but while selecting a match to apply. it is difficult to understand which match will update me with next rule. Because some matches won't produce anything even if we apply them. So if possible it is better to have one match at a time.

**Comment by anthonyanjorin** [comment] 2019-05-15 11:55
How about just numbering the matches?  The match objects have a unique Java id (hashcode), which can be mapped to a simple int that gets incremented for each rule?

**Comment by LegionaryCohort** [comment] 2019-05-15 11:58
@shub1989 I think there is a misunderstanding here of how IBeX works. If there are multiple matches for a given rule, it may very well be the case that the user wants to apply a specific match, rather than just any match for that rule. So it doesn't make sense to limit the matches being displayed.
However, I can see an argument being made for giving the option to "Apply rule", which will simply pick one of the available matches for that rule at random. Not sure how useful this would really be though...

@anthonyanjorin I was thinking that perhaps there could be a little more information conveyed through the textual representation (so the user doesn't have to click through them to find the one he wanted). But numbering will certainly work.

**Comment by anthonyanjorin** [comment] 2019-05-15 12:29
I personally don’t see the need for a random Apply Rule option.  The whole point of victory is to control the process.

Hmm...  some textual identifier would be nice - but I have no idea how to do this meaningfully.  One could support renaming the matches perhaps?  I expect this to be an unnecessary luxury feature though...

Important is to be able to know which matches were there before and which are new - and this can be realised by numbering and sorting the matches.

**Comment by 09Ankita** [comment] 2019-05-15 16:20
@LegionaryCohort Isn't this "Important is to be able to know which matches were there before and which are new - and this can be realised by numbering and sorting the matches." similar to filtering the match through rank (sort them by age), a task on which Core is currently working on.

**Comment by anthonyanjorin** [comment] 2019-05-15 16:57
Absolutely:  age == numbering

(I am not supervising core so don’t know exactly what they are doing right now)

**Comment by 09Ankita** [comment] 2019-05-28 07:52
Based upon this "Absolutely: age == numbering", I am assigning this issue to Asher, from Core, as he working on a similar task. 

(Mentioning this as the main Title of the issue differs from this, but from the discussion it's concluded on numbering and sorting through Age)

**Comment by asher636** [comment] 2019-06-17 16:35
I already implemented this task and is related to feature "match_age" on branch: [https://github.com/eMoflon/emoflon-ibex/commits/victory-monitor_match-age]

**Comment by asher636** [comment] 2019-06-17 16:37
I already implemented this and is related to:
[](https://github.com/eMoflon/emoflon-ibex/commits/victory-monitor_match-age)

**Comment by LegionaryCohort** [comment] 2019-07-16 20:39
The "birth-step" of matches is now used to generate a unique name for each match.

The specific name is constructed as follows:
"`<rule name>` #`<birth step>`[.`<optional additional identifier>`]"
Where the additional identifier is added whenever multiple matches appear for the same rule in the same step.

**Closed by LegionaryCohort** 2019-07-16 20:39 UTC
Labels: Victory, enhancement
