### ISSUE TITLE
[Victory] Reset button

### ISSUE THREAD

**Issue by saman** [eMoflon/emoflon-ibex-ui#178] opened 2019-07-19 08:50 UTC
I think it will be good if we have a reset button. So, the user can reset the whole model and start making it from scratch.

Right now the user has to use the quit button and run the Victory again.

**Comment by LegionaryCohort** [comment] 2019-07-19 13:27
Effectively a duplicate of #183

**Closed by LegionaryCohort** 2019-07-19 13:27 UTC
Labels: FeatureRequest, Victory
